### ISSUE TITLE
MSSQL: Update connector documentation to reflect TLS support

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#1168] opened 2020-03-24 12:53 UTC
## Description

The document needs to be updated to reflect support for sslmode

## Acceptance Criteria
- [ ] Documentation updated
- [ ] Known limitations updated

**Comment by izgeri** [comment] 2020-04-07 21:16
Closing as duplicate of cyberark/secretless-docs#246

**Closed by izgeri** 2020-04-07 21:16 UTC
Labels: component/secretless-broker, kind/documentation, triage/duplicate
