### ISSUE TITLE
Secretless-broker 1.2.x is XAd

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#962] opened 2019-10-24 13:17 UTC
AC:
- [ ] Performance metrics of the new implementation are gathered (TBD)

Data output (prelim):
- https://gist.github.com/sgnn7/f4e961dc5cca272cfd25aa30d7fe7558

**Comment by sgnn7** [comment] 2019-10-24 15:22
Plan (10thread):
- [ ] 6hr/PG/norecreate ->
- [ ] 6hr/MySQLl/norecreate ->
- [ ] 6hr/PG/recreate ->
- [ ] 6hr/MySQL/recreate ->
- [ ] 4day/PG/norecreate ->
- [ ] 4day/MySQL/norecreate ->
- …

**Comment by izgeri** [comment] 2019-10-24 17:10
@sgnn7 is this a duplicate of #864?

**Comment by sgnn7** [comment] 2019-10-24 17:55
Seems like it though this one has more details at this point

**Comment by izgeri** [comment] 2019-10-25 14:57
it's not a lot, though. I'll copy it over and close this issue.

**Closed by izgeri** 2019-10-25 14:57 UTC
Labels: component/secretless-broker, kind/XA, triage/duplicate
