### ISSUE TITLE
Add missing plugin APIs

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#965] opened 2019-10-24 19:05 UTC
Since the refactor, we have lost public APIs that need to be restored at some point

AC:
- [ ] There are public APIs for providers
- [ ] There are public APIs for configuration managers
- [ ] There are public APIs for connection managers

**Comment by izgeri** [comment] 2020-01-10 20:34
Closed as duplicate of #834

**Closed by izgeri** 2020-01-10 20:34 UTC
Labels: component/secretless-broker, component/secretless-plugins, kind/technical-debt, triage/duplicate
